spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
