apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarthome-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /api/v1/heating
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.monolith.name }}-service
              port:
                number: {{ .Values.monolith.port  }}

        - path: /api/v1/commands
          pathType: Prefix
          backend:  
            service:
              name: {{ .Values.commands.name }}-service
              port:
                number: {{ .Values.commands.port  }}

        - path: /api/v1/telemetry
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.telemetry.name }}-service
              port:
                number: {{ .Values.telemetry.port  }}
