kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.kafka.name }}-pvc
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "smart-home.appLabels" .Values.kafka | nindent 4 }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.kafka.name }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/smarthome/kafka
