apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafka.name }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.kafka.name }}-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.kafka.name }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kafka.name }}-clusterrole
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ .Values.kafka.name }}-sa