apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.name }}-cm-initdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-home.appLabels" .Values.postgresql | nindent 4 }}
data:
  init.sql: |
    {{ range .Files.Lines "postgresql/init.sql" }}
    {{ . }}{{ end }}
